# Generated by Django 2.2.5 on 2020-04-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_id', models.IntegerField(verbose_name='所屬投票主題')),
                ('title', models.CharField(max_length=100, verbose_name='選項文字')),
                ('count', models.IntegerField(default=0, verbose_name='票數')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='投票主題')),
                ('desc', models.TextField(max_length=512, verbose_name='說明')),
                ('create', models.DateField(auto_now_add=True, verbose_name='建立時間')),
            ],
        ),
    ]
